#!/usr/bin/perl

=head1 Description

Drop database from ensembl server using db commands

=cut

use strict;
use warnings;

my ($server, $db_name) = @ARGV;

die "Usage: dbc_drop mysql-ens-compara-prod-X db_name\n\n" unless $server && $db_name;

my $server_rw;
if ( $server =~ /-eg-/ ) {
    $server_rw = "$server-ensrw";
} else {
    $server_rw = "$server-ensadmin";
}

my $cmd = "standaloneJob.pl Bio::EnsEMBL::Hive::RunnableDB::DatabaseDumper -exclude_list 1 -db_conn \$($server_rw details url)$db_name -output_file ${db_name}.sql.gz &> /dev/null";
print "Backing up eHive tables from $db_name into ${db_name}.sql.gz\n";
system($cmd) == 0
    or die "'$cmd' failed: $?";

$cmd = "$server_rw -e 'drop database $db_name'";
print "$cmd\n";
system($cmd);
